### ISSUE TITLE
Customize datasets tutorial cant work

### ISSUE THREAD

**Issue by cgxjdzz** [microsoft/Semi-supervised-learning#23]
## Bug

When running the function _get_algorithm_ , a class like FixMatch will be created which has a super class _AlgorithmBase_ . In this super class, some datasets and dataloaders have to be created with some given public dataset rather than mine.

### Reproduce the Bug

Simply using the colab u will find it

### Error Messages and Logs

[/usr/local/lib/python3.7/dist-packages/semilearn/algorithms/__init__.py](https://localhost:8080/#) in get_algorithm(args, net_builder, tb_log, logger)
     47             net_builder=net_builder,
     48             tb_log=tb_log,
---> 49             logger=logger
     50         )
     51         return alg

[/usr/local/lib/python3.7/dist-packages/semilearn/algorithms/fixmatch/fixmatch.py](https://localhost:8080/#) in __init__(self, args, net_builder, tb_log, logger)
     31     """
     32     def __init__(self, args, net_builder, tb_log=None, logger=None):
---> 33         super().__init__(args, net_builder, tb_log, logger)
     34         # fixmatch specificed arguments
     35         self.init(T=args.T, p_cutoff=args.p_cutoff, hard_label=args.hard_label)

[/usr/local/lib/python3.7/dist-packages/semilearn/core/algorithmbase.py](https://localhost:8080/#) in __init__(self, args, net_builder, tb_log, logger, **kwargs)
     77 
     78         # build dataset
---> 79         self.dataset_dict = self.set_dataset()
     80 
     81         # build data loader

[/usr/local/lib/python3.7/dist-packages/semilearn/core/algorithmbase.py](https://localhost:8080/#) in set_dataset(self)
    107         if self.rank != 0 and self.distributed:
    108             torch.distributed.barrier()
--> 109         dataset_dict = get_dataset(self.args, self.algorithm, self.args.dataset, self.args.num_labels, self.args.num_classes, self.args.data_dir)
    110         self.args.ulb_dest_len = len(dataset_dict['train_ulb']) if dataset_dict['train_ulb'] is not None else 0
    111         self.args.lb_dest_len = len(dataset_dict['train_lb'])

[/usr/local/lib/python3.7/dist-packages/semilearn/core/utils/build.py](https://localhost:8080/#) in get_dataset(args, algorithm, dataset, num_labels, num_classes, data_dir, include_lb_to_ulb)
    103         lb_dset, ulb_dset, eval_dset, test_dset = get_json_dset(args, algorithm, dataset, num_labels, num_classes, data_dir=data_dir, include_lb_to_ulb=include_lb_to_ulb)
    104     else:
--> 105         raise NotImplementedError
    106 
    107     dataset_dict = {'train_lb': lb_dset, 'train_ulb': ulb_dset, 'eval': eval_dset, 'test': test_dset}

**Comment by Hhhhhhao** [comment]
Hi, I have fixed the colab for custom dataset. The reason it fails is due to 'none' in set for dataset in the config dict, which is not supported for not creating a dataset yet.

**Comment by cgxjdzz** [comment]
Thanks a lot! So this parameter has no influence on the following process?

**Comment by Hhhhhhao** [comment]
It only controls which dataset to be created. And for semilearn package we decide to re-create the dataset and data loader outside the trainer.

The 'none' option will be supported in next update to avoid the re-creation.

**Comment by cgxjdzz** [comment]
I totally understand after reviewing the code.  There are some methods like **train** or **evaluate** in class _AlgorithmBase_ , which didn't be used in the whole process. And the dataset and dataloader created in the algorithm won't affect model training or predicting. I suppose you will delete these parameters and methods in the next version.

**Comment by shakediel** [comment]
hey, 
this issue is still relevant in the current version
the default dataset is `mnist` and it does not exist inside the `get_dataset` method

**Comment by dddZhao** [comment]
Hi, I still met this problem when I run the code locally. How to solve it?
